import { useEffect, useState } from 'react'
import axios from 'axios'
import Head from 'next/head'

export default function Home() {
  const [suggestions, setSuggestions] = useState([])

  useEffect(() => {
    axios.get('/api/v1/suggestions').then(({ data }) => setSuggestions(data.suggestions))
  }, [])

  return (
    <div>
      <Head>
        <title>PickyEats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Suggestions</h1>
      <ul>
        {suggestions.map((suggestion) => (
          <li key={suggestion.id}>{suggestion.name}</li>
        ))}
      </ul>
    </div>
  )
}
